# -----------------------------------------------------------------------------
# File: backend/app/domain/mentor_service.py
#
# Description:
# Mentor advice service for AppNest.
#
# Responsibilities:
# - Provide fallback mentor tips when AI advice is unavailable
# - Maintain backward compatibility with legacy calls
# - Ensure system stability if AI fails
#
# Architecture Rule:
# Gemini AI calls must NOT happen here.
# AI generation is handled centrally by ExperienceEngine.
#
# Stability Features:
# - Safe handling of missing user/result
# - Compatible with ModuleResult and dictionary result objects
# -----------------------------------------------------------------------------

import random
from typing import Optional, Union
from app.platform.module_result import ModuleResult


class MentorService:

    GENERIC_TIPS = [

        "Consistency is key! Keep practicing to improve your score 📈",

        "Don't forget to take breaks. A fresh mind performs better 🧠",

        "Every session teaches you something new. Keep going! 🚀",

        "Even pros were beginners once. Show up, and you'll level up 💪",

        "Focus on the process, not just the score. Growth is the goal 🎯",

        "Patterns appear with practice. Pay attention to mistakes.",

        "Slow down. Accuracy beats speed every time.",

        "Short sessions repeated daily beat long sessions once a week."
    ]

    # -------------------------------------------------------------------------
    # MAIN ADVICE GENERATOR
    # -------------------------------------------------------------------------
    @staticmethod
    def get_advice(
        module_key: str,
        result: Optional[Union[ModuleResult, dict]] = None,
        user=None
    ) -> str:

        """
        Generate mentor advice.

        AI advice should already be generated by ExperienceEngine.
        This function provides fallback advice only.
        """

        # Extract username safely
        username = "Player"
        if user and getattr(user, "username", None):
            username = user.username

        # Extract score safely
        score = 0

        if isinstance(result, dict):

            score = result.get("score", 0)

        elif isinstance(result, ModuleResult):

            score = result.score

        # Performance-based tips
        if score == 0:

            return "Start slow. Understand the mechanics before pushing speed."

        if score < 50:

            return "Focus on accuracy first. Speed improves naturally."

        if score < 80:

            return "You're improving. Now refine your strategy."

        if score >= 80:

            return "Strong performance. Try increasing the challenge."

        # Generic fallback
        return random.choice(MentorService.GENERIC_TIPS)

    # -------------------------------------------------------------------------
    # GENERIC TIP (UTILITY METHOD)
    # -------------------------------------------------------------------------
    @staticmethod
    def fallback_tip():

        return random.choice(
            MentorService.GENERIC_TIPS
        )
