"""initial create all tables

Revision ID: 6992616b2a82
Revises: 
Create Date: 2026-02-18 12:26:30.363551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6992616b2a82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game_sessions', sa.Column('game_key', sa.String(length=80), nullable=False))
    op.add_column('game_sessions', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('game_sessions', sa.Column('metadata', sa.Text(), nullable=True))
    op.alter_column('game_sessions', 'score',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('game_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_constraint('game_sessions_ibfk_1', 'game_sessions', type_='foreignkey')
    op.drop_column('game_sessions', 'difficulty')
    op.drop_column('game_sessions', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('game_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('game_sessions', sa.Column('difficulty', mysql.VARCHAR(length=20), nullable=True))
    op.create_foreign_key('game_sessions_ibfk_1', 'game_sessions', 'users', ['user_id'], ['id'])
    op.alter_column('game_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('game_sessions', 'score',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('game_sessions', 'metadata')
    op.drop_column('game_sessions', 'duration_seconds')
    op.drop_column('game_sessions', 'game_key')
    op.drop_table('profile_metrics')
    op.drop_table('achievements')
    # ### end Alembic commands ###
