"""add capabilities and xp_reward_base to module

Revision ID: e55667780dc6
Revises: efd5e3f4d9d5
Create Date: 2026-02-26 12:56:38.637680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55667780dc6'
down_revision: Union[str, None] = 'efd5e3f4d9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('capabilities', sa.JSON(), nullable=True))
    op.add_column('modules', sa.Column('xp_reward_base', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'xp_reward_base')
    op.drop_column('modules', 'capabilities')
    # ### end Alembic commands ###
